"""Core domain types used throughout Sentinel-X."""

from __future__ import annotations

from sentinel_x.core.bus import (
    EventBus,
    HandlerFailure,
    PublishReport,
    Subscription,
)
from sentinel_x.core.engine import (
    EngineRunConflictError,
    EngineSnapshot,
    SentinelEngine,
)
from sentinel_x.core.execution import (
    CollectorExecutionError,
    CollectorExecutionFailure,
    CollectorExecutionOutcome,
    CollectorExecutionPolicy,
    CollectorExecutionSpec,
    CollectorExecutionSnapshot,
    CollectorExecutionStatus,
    CollectorExecutionValidationError,
    CollectorExecutor,
    CollectorSpecMismatchError,
    ExecutionClockError,
    UnknownExecutionStateError,
)
from sentinel_x.core.events import (
    EventKind,
    EventSeverity,
    SentinelEvent,
)
from sentinel_x.core.registry import (
    CollectorDefinition,
    CollectorDefinitionValidationError,
    CollectorRegistry,
    CollectorRegistryBindingError,
    CollectorRegistryError,
    CollectorRuntimeSettings,
    DuplicateCollectorDefinitionError,
    UnknownCollectorDefinitionError,
)
from sentinel_x.core.runtime import (
    CollectorEmissionResult,
    CollectorPublicationTransaction,
    CollectorRuntime,
    CollectorRuntimeClockError,
    CollectorRuntimeContractError,
    CollectorRuntimeCycle,
    CollectorRuntimeError,
    CollectorRuntimeSnapshot,
)
from sentinel_x.core.scheduling import (
    CollectorDispatch,
    CollectorExecutionState,
    CollectorSchedule,
    CollectorScheduler,
    CollectorScheduleSnapshot,
    DuplicateScheduleError,
    ScheduleStateError,
    ScheduleValidationError,
    SchedulerClockError,
    SchedulingError,
    UnknownScheduleError,
)
from sentinel_x.core.state import (
    AgentLifecycle,
    AgentState,
    InvalidStateTransitionError,
)

__all__ = [
    "AgentLifecycle",
    "AgentState",
    "CollectorDefinition",
    "CollectorDefinitionValidationError",
    "CollectorDispatch",
    "CollectorExecutionError",
    "CollectorExecutionFailure",
    "CollectorExecutionOutcome",
    "CollectorExecutionPolicy",
    "CollectorExecutionSpec",
    "CollectorExecutionSnapshot",
    "CollectorExecutionState",
    "CollectorExecutionStatus",
    "CollectorExecutionValidationError",
    "CollectorExecutor",
    "CollectorRegistry",
    "CollectorRegistryBindingError",
    "CollectorRegistryError",
    "CollectorEmissionResult",
    "CollectorPublicationTransaction",
    "CollectorRuntime",
    "CollectorRuntimeClockError",
    "CollectorRuntimeContractError",
    "CollectorRuntimeCycle",
    "CollectorRuntimeError",
    "CollectorRuntimeSnapshot",
    "CollectorRuntimeSettings",
    "CollectorSchedule",
    "CollectorScheduler",
    "CollectorScheduleSnapshot",
    "CollectorSpecMismatchError",
    "DuplicateCollectorDefinitionError",
    "DuplicateScheduleError",
    "EngineRunConflictError",
    "EngineSnapshot",
    "EventBus",
    "EventKind",
    "EventSeverity",
    "ExecutionClockError",
    "HandlerFailure",
    "InvalidStateTransitionError",
    "PublishReport",
    "ScheduleStateError",
    "ScheduleValidationError",
    "SchedulerClockError",
    "SchedulingError",
    "SentinelEngine",
    "SentinelEvent",
    "Subscription",
    "UnknownCollectorDefinitionError",
    "UnknownExecutionStateError",
    "UnknownScheduleError",
]
